main:
  - name: হোম
    url: '/bn/#about'
    weight: 10
  - name: গবেষণা
    url: '/bn/#research'
    weight: 20
  - name: অর্থায়ন
    url: '/bn/#projects'
    weight: 25
  - name: দল
    url: '/bn/#team'
    weight: 30
  - name: প্রকাশনা
    url: '/bn/#publication'
    weight: 40
  - name: পাঠদান
    url: '/bn/#teaching'
    weight: 45
  - name: সংবাদ
    url: '/bn/#news'
    weight: 50
  - name: আউটরিচ
    url: '/#outreach'
    weight: 60
  - name: যোগাযোগ
    url: '/#contact'
    weight: 70