#!/usr/bin/env python3
"""Write metrics.tex (citation metrics data) for the CV's metrics panel.

Inputs (all in this folder, produced by latexrun.ps1 Steps 1-2):
  PoPMetrics.csv   one row of Publish or Perish metrics ('c' = citations, 'h' = h-index)
  PoPCites.csv     one row per paper (column 'Cites'), used for the i10-index
  PoPAuthYear.csv  Year,Cites — correct for every year except the last, which is
                   recalculated here as total citations minus all earlier years.

Output: metrics.tex — plain \\def data only; the layout lives in buetcv.cls
(\\cvmetricspanel). The file is rewritten from scratch on every run.
"""
import datetime as dt
import sys

import pandas as pd

YEARS_SHOWN = 8


def main() -> int:
    metrics = pd.read_csv("PoPMetrics.csv").iloc[0].to_dict()
    total_citations = int(metrics.get("c", 0))
    h_index = int(metrics.get("h", 0))
    # PoP has no i10 metric ('hc' is the contemporary h-index), so count
    # papers with at least 10 citations, as Google Scholar does.
    i10_index = int((pd.read_csv("PoPCites.csv")["Cites"] >= 10).sum())

    years = pd.read_csv("PoPAuthYear.csv")
    if len(years) < 2:
        print("ERROR: PoPAuthYear.csv needs at least two years.")
        return 1
    years.loc[years.index[-1], "Cites"] = total_citations - int(years["Cites"][:-1].sum())
    shown = years.tail(YEARS_SHOWN).astype({"Year": int, "Cites": int})
    full, partial = shown.iloc[:-1], shown.iloc[-1:]
    current_year = int(partial["Year"].iloc[0])

    def table(df: pd.DataFrame) -> str:
        return "year cites\n" + "".join(f"{y} {c}\n" for y, c in zip(df["Year"], df["Cites"]))

    today = dt.date.today()
    text = (
        "% metrics.tex — generated by pycv_update_gscholar_tex.py; do not edit by hand.\n"
        f"\\def\\gsCitations{{{total_citations:,}}}\n"
        f"\\def\\gsHindex{{{h_index}}}\n"
        f"\\def\\gsIten{{{i10_index}}}\n"
        f"\\def\\gsRetrieved{{{today.day} {today:%B %Y}}}\n"
        f"\\def\\gsCurrentYear{{{current_year}}}\n"
        f"\\def\\gsYearTicks{{{','.join(str(y) for y in shown['Year'])}}}\n"
        f"\\pgfplotstableread{{\n{table(full)}}}\\gsFullYears\n"
        f"\\pgfplotstableread{{\n{table(partial)}}}\\gsPartialYear\n"
    )
    with open("metrics.tex", "w", encoding="utf-8") as f:
        f.write(text)

    print(f"           Citations {total_citations}, h-index {h_index}, i10-index {i10_index}")
    print(f"           Per year: " + ", ".join(f"{y}: {c}" for y, c in zip(shown["Year"], shown["Cites"]))
          + f" ({current_year} to date)")
    print("           metrics.tex written.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
